# Generated by Django 5.2.5 on 2025-09-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riotstats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='timestamp',
        ),
    ]
